//
// Created by Hedzr Yeh on 2021/10/4.
//

#ifndef DESIGN_PATTERNS_CXX_DESIGN_PATTERNS_CXX_HH
#define DESIGN_PATTERNS_CXX_DESIGN_PATTERNS_CXX_HH

#include "design_patterns/dp.hh"

#endif //DESIGN_PATTERNS_CXX_DESIGN_PATTERNS_CXX_HH
